// Flag image URL from flagcdn.com (works on all platforms)
function flagUrl(code) {
  return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
}

const COUNTRIES = [
  { code: "AF", name: "Afghanistan", phoneFormat: "XX XXX XXXX" },
  { code: "AL", name: "Albania", phoneFormat: "XX XXX XXXX" },
  { code: "DZ", name: "Algeria", phoneFormat: "XX XXX XXXX" },
  { code: "AD", name: "Andorra", phoneFormat: "XXX XXX" },
  { code: "AO", name: "Angola", phoneFormat: "XXX XXX XXX" },
  { code: "AG", name: "Antigua and Barbuda", phoneFormat: "XXX XXXX" },
  { code: "AR", name: "Argentina", phoneFormat: "XX XXXX XXXX" },
  { code: "AM", name: "Armenia", phoneFormat: "XX XXX XXX" },
  { code: "AU", name: "Australia", phoneFormat: "X XXXX XXXX" },
  { code: "AT", name: "Austria", phoneFormat: "XXX XXX XXX" },
  { code: "AZ", name: "Azerbaijan", phoneFormat: "XX XXX XX XX" },
  { code: "BS", name: "Bahamas", phoneFormat: "XXX XXXX" },
  { code: "BH", name: "Bahrain", phoneFormat: "XXXX XXXX" },
  { code: "BD", name: "Bangladesh", phoneFormat: "XXXX XXX XXX" },
  { code: "BB", name: "Barbados", phoneFormat: "XXX XXXX" },
  { code: "BY", name: "Belarus", phoneFormat: "XX XXX XX XX" },
  { code: "BE", name: "Belgium", phoneFormat: "XXX XX XX XX" },
  { code: "BZ", name: "Belize", phoneFormat: "XXX XXXX" },
  { code: "BJ", name: "Benin", phoneFormat: "XX XX XX XX" },
  { code: "BT", name: "Bhutan", phoneFormat: "XX XX XX XX" },
  { code: "BO", name: "Bolivia", phoneFormat: "X XXX XXXX" },
  { code: "BA", name: "Bosnia and Herzegovina", phoneFormat: "XX XXX XXX" },
  { code: "BW", name: "Botswana", phoneFormat: "XX XXX XXX" },
  { code: "BR", name: "Brazil", phoneFormat: "XX XXXXX XXXX" },
  { code: "BN", name: "Brunei", phoneFormat: "XXX XXXX" },
  { code: "BG", name: "Bulgaria", phoneFormat: "XX XXX XXX" },
  { code: "BF", name: "Burkina Faso", phoneFormat: "XX XX XX XX" },
  { code: "BI", name: "Burundi", phoneFormat: "XX XX XX XX" },
  { code: "CV", name: "Cabo Verde", phoneFormat: "XXX XX XX" },
  { code: "KH", name: "Cambodia", phoneFormat: "XX XXX XXX" },
  { code: "CM", name: "Cameroon", phoneFormat: "XXXX XX XX" },
  { code: "CA", name: "Canada", phoneFormat: "XXX XXX XXXX" },
  { code: "CF", name: "Central African Republic", phoneFormat: "XX XX XX XX" },
  { code: "TD", name: "Chad", phoneFormat: "XX XX XX XX" },
  { code: "CL", name: "Chile", phoneFormat: "X XXXX XXXX" },
  { code: "CN", name: "China", phoneFormat: "XXX XXXX XXXX" },
  { code: "CO", name: "Colombia", phoneFormat: "XXX XXX XXXX" },
  { code: "KM", name: "Comoros", phoneFormat: "XX XX XX" },
  { code: "CG", name: "Congo", phoneFormat: "XX XXX XXXX" },
  { code: "CD", name: "Congo (DRC)", phoneFormat: "XX XXX XXXX" },
  { code: "CR", name: "Costa Rica", phoneFormat: "XXXX XXXX" },
  { code: "CI", name: "Côte d'Ivoire", phoneFormat: "XX XX XX XX" },
  { code: "HR", name: "Croatia", phoneFormat: "XX XXX XXX" },
  { code: "CU", name: "Cuba", phoneFormat: "X XXX XXXX" },
  { code: "CY", name: "Cyprus", phoneFormat: "XX XXX XXX" },
  { code: "CZ", name: "Czech Republic", phoneFormat: "XXX XXX XXX" },
  { code: "DK", name: "Denmark", phoneFormat: "XX XX XX XX" },
  { code: "DJ", name: "Djibouti", phoneFormat: "XX XX XX XX" },
  { code: "DM", name: "Dominica", phoneFormat: "XXX XXXX" },
  { code: "DO", name: "Dominican Republic", phoneFormat: "XXX XXX XXXX" },
  { code: "EC", name: "Ecuador", phoneFormat: "XX XXX XXXX" },
  { code: "EG", name: "Egypt", phoneFormat: "XX XXX XXXX" },
  { code: "SV", name: "El Salvador", phoneFormat: "XXXX XXXX" },
  { code: "GQ", name: "Equatorial Guinea", phoneFormat: "XX XXX XXXX" },
  { code: "ER", name: "Eritrea", phoneFormat: "X XXX XXX" },
  { code: "EE", name: "Estonia", phoneFormat: "XXX XXXX" },
  { code: "SZ", name: "Eswatini", phoneFormat: "XX XX XX XX" },
  { code: "ET", name: "Ethiopia", phoneFormat: "XX XXX XXXX" },
  { code: "FJ", name: "Fiji", phoneFormat: "XXX XXXX" },
  { code: "FI", name: "Finland", phoneFormat: "XX XXX XXXX" },
  { code: "FR", name: "France", phoneFormat: "XX XX XX XX XX" },
  { code: "GA", name: "Gabon", phoneFormat: "X XX XX XX" },
  { code: "GM", name: "Gambia", phoneFormat: "XXX XXXX" },
  { code: "GE", name: "Georgia", phoneFormat: "XXX XXX XXX" },
  { code: "DE", name: "Germany", phoneFormat: "XXX XXXXXXX" },
  { code: "GH", name: "Ghana", phoneFormat: "XX XXX XXXX" },
  { code: "GR", name: "Greece", phoneFormat: "XXX XXX XXXX" },
  { code: "GD", name: "Grenada", phoneFormat: "XXX XXXX" },
  { code: "GT", name: "Guatemala", phoneFormat: "XXXX XXXX" },
  { code: "GN", name: "Guinea", phoneFormat: "XX XXXX XX" },
  { code: "GW", name: "Guinea-Bissau", phoneFormat: "X XXXXXX" },
  { code: "GY", name: "Guyana", phoneFormat: "XXX XXXX" },
  { code: "HT", name: "Haiti", phoneFormat: "XX XX XXXX" },
  { code: "HN", name: "Honduras", phoneFormat: "XXXX XXXX" },
  { code: "HU", name: "Hungary", phoneFormat: "XX XXX XXXX" },
  { code: "IS", name: "Iceland", phoneFormat: "XXX XXXX" },
  { code: "IN", name: "India", phoneFormat: "XXXXX XXXXX" },
  { code: "ID", name: "Indonesia", phoneFormat: "XXX XXXX XXXX" },
  { code: "IR", name: "Iran", phoneFormat: "XXX XXX XXXX" },
  { code: "IQ", name: "Iraq", phoneFormat: "XXX XXX XXXX" },
  { code: "IE", name: "Ireland", phoneFormat: "XX XXX XXXX" },
  { code: "IT", name: "Italy", phoneFormat: "XXX XXX XXXX" },
  { code: "JM", name: "Jamaica", phoneFormat: "XXX XXXX" },
  { code: "JP", name: "Japan", phoneFormat: "X XXXX XXXX" },
  { code: "JO", name: "Jordan", phoneFormat: "X XXXX XXXX" },
  { code: "KZ", name: "Kazakhstan", phoneFormat: "XXX XXX XXXX" },
  { code: "KE", name: "Kenya", phoneFormat: "XXX XXX XXX" },
  { code: "KI", name: "Kiribati", phoneFormat: "XX XXX" },
  { code: "XK", name: "Kosovo", phoneFormat: "XX XXX XXX" },
  { code: "KW", name: "Kuwait", phoneFormat: "XXXX XXXX" },
  { code: "KG", name: "Kyrgyzstan", phoneFormat: "XXX XXX XXX" },
  { code: "LA", name: "Laos", phoneFormat: "XX XX XX XX" },
  { code: "LV", name: "Latvia", phoneFormat: "XX XXX XXX" },
  { code: "LB", name: "Lebanon", phoneFormat: "X XXX XXX" },
  { code: "LS", name: "Lesotho", phoneFormat: "X XXX XXXX" },
  { code: "LR", name: "Liberia", phoneFormat: "XX XXX XXXX" },
  { code: "LY", name: "Libya", phoneFormat: "XX XXX XXXX" },
  { code: "LI", name: "Liechtenstein", phoneFormat: "XXX XXXX" },
  { code: "LT", name: "Lithuania", phoneFormat: "XXX XX XXX" },
  { code: "LU", name: "Luxembourg", phoneFormat: "XXX XXX XXX" },
  { code: "MG", name: "Madagascar", phoneFormat: "XX XX XXX XX" },
  { code: "MW", name: "Malawi", phoneFormat: "XXX XXX XXX" },
  { code: "MY", name: "Malaysia", phoneFormat: "X XXXX XXXX" },
  { code: "MV", name: "Maldives", phoneFormat: "XXX XXXX" },
  { code: "ML", name: "Mali", phoneFormat: "XX XX XX XX" },
  { code: "MT", name: "Malta", phoneFormat: "XXXX XXXX" },
  { code: "MH", name: "Marshall Islands", phoneFormat: "XXX XXXX" },
  { code: "MR", name: "Mauritania", phoneFormat: "XX XX XX XX" },
  { code: "MU", name: "Mauritius", phoneFormat: "XXX XXXX" },
  { code: "MX", name: "Mexico", phoneFormat: "XXX XXX XXXX" },
  { code: "FM", name: "Micronesia", phoneFormat: "XXX XXXX" },
  { code: "MD", name: "Moldova", phoneFormat: "XXX XX XXX" },
  { code: "MC", name: "Monaco", phoneFormat: "XX XX XX XX" },
  { code: "MN", name: "Mongolia", phoneFormat: "XX XXXX XXXX" },
  { code: "ME", name: "Montenegro", phoneFormat: "XX XXX XXX" },
  { code: "MA", name: "Morocco", phoneFormat: "XX XXX XXXX" },
  { code: "MZ", name: "Mozambique", phoneFormat: "XX XXX XXXX" },
  { code: "MM", name: "Myanmar", phoneFormat: "XX XXX XXX" },
  { code: "NA", name: "Namibia", phoneFormat: "XX XXX XXXX" },
  { code: "NR", name: "Nauru", phoneFormat: "XXX XXXX" },
  { code: "NP", name: "Nepal", phoneFormat: "XXX XXX XXXX" },
  { code: "NL", name: "Netherlands", phoneFormat: "XX XXX XXXX" },
  { code: "NZ", name: "New Zealand", phoneFormat: "X XXX XXXX" },
  { code: "NI", name: "Nicaragua", phoneFormat: "XXXX XXXX" },
  { code: "NE", name: "Niger", phoneFormat: "XX XX XX XX" },
  { code: "NG", name: "Nigeria", phoneFormat: "XXX XXX XXXX" },
  { code: "KP", name: "North Korea", phoneFormat: "XXX XXX XXXX" },
  { code: "MK", name: "North Macedonia", phoneFormat: "XX XXX XXX" },
  { code: "NO", name: "Norway", phoneFormat: "XXX XX XXX" },
  { code: "OM", name: "Oman", phoneFormat: "XX XXX XXXX" },
  { code: "PK", name: "Pakistan", phoneFormat: "XXX XXX XXXX" },
  { code: "PW", name: "Palau", phoneFormat: "XXX XXXX" },
  { code: "PS", name: "Palestine", phoneFormat: "XX XXX XXXX" },
  { code: "PA", name: "Panama", phoneFormat: "XXX XXXX" },
  { code: "PG", name: "Papua New Guinea", phoneFormat: "XXX XXXX" },
  { code: "PY", name: "Paraguay", phoneFormat: "XX XXX XXXX" },
  { code: "PE", name: "Peru", phoneFormat: "XXX XXX XXX" },
  { code: "PH", name: "Philippines", phoneFormat: "XXX XXX XXXX" },
  { code: "PL", name: "Poland", phoneFormat: "XXX XXX XXX" },
  { code: "PT", name: "Portugal", phoneFormat: "XX XXX XXXX" },
  { code: "QA", name: "Qatar", phoneFormat: "XXXX XXXX" },
  { code: "RO", name: "Romania", phoneFormat: "XXX XXX XXX" },
  { code: "RU", name: "Russia", phoneFormat: "XXX XXX XX XX" },
  { code: "RW", name: "Rwanda", phoneFormat: "XXX XXX XXX" },
  { code: "KN", name: "Saint Kitts and Nevis", phoneFormat: "XXX XXXX" },
  { code: "LC", name: "Saint Lucia", phoneFormat: "XXX XXXX" },
  { code: "VC", name: "Saint Vincent and the Grenadines", phoneFormat: "XXX XXXX" },
  { code: "WS", name: "Samoa", phoneFormat: "XX XXXX" },
  { code: "SM", name: "San Marino", phoneFormat: "XXXX XX XX" },
  { code: "ST", name: "Sao Tome and Principe", phoneFormat: "XX XXXX" },
  { code: "SA", name: "Saudi Arabia", phoneFormat: "XX XXX XXXX" },
  { code: "SN", name: "Senegal", phoneFormat: "XX XXX XX XX" },
  { code: "RS", name: "Serbia", phoneFormat: "XX XXX XXXX" },
  { code: "SC", name: "Seychelles", phoneFormat: "X XXX XXX" },
  { code: "SL", name: "Sierra Leone", phoneFormat: "XX XXX XXXX" },
  { code: "SG", name: "Singapore", phoneFormat: "XXXX XXXX" },
  { code: "SK", name: "Slovakia", phoneFormat: "XXX XXX XXX" },
  { code: "SI", name: "Slovenia", phoneFormat: "XX XXX XXX" },
  { code: "SB", name: "Solomon Islands", phoneFormat: "XX XXXX" },
  { code: "SO", name: "Somalia", phoneFormat: "X XXX XXX" },
  { code: "ZA", name: "South Africa", phoneFormat: "XX XXX XXXX" },
  { code: "KR", name: "South Korea", phoneFormat: "XX XXXX XXXX" },
  { code: "SS", name: "South Sudan", phoneFormat: "XXX XXX XXX" },
  { code: "ES", name: "Spain", phoneFormat: "XXX XX XX XX" },
  { code: "LK", name: "Sri Lanka", phoneFormat: "XX XXX XXXX" },
  { code: "SD", name: "Sudan", phoneFormat: "XX XXX XXXX" },
  { code: "SR", name: "Suriname", phoneFormat: "XXX XXX" },
  { code: "SE", name: "Sweden", phoneFormat: "XX XXX XX XX" },
  { code: "CH", name: "Switzerland", phoneFormat: "XX XXX XX XX" },
  { code: "SY", name: "Syria", phoneFormat: "XX XXX XXXX" },
  { code: "TW", name: "Taiwan", phoneFormat: "X XXXX XXXX" },
  { code: "TJ", name: "Tajikistan", phoneFormat: "XX XXX XX XX" },
  { code: "TZ", name: "Tanzania", phoneFormat: "XXX XXX XXX" },
  { code: "TH", name: "Thailand", phoneFormat: "XX XXX XXXX" },
  { code: "TL", name: "Timor-Leste", phoneFormat: "XXX XXXX" },
  { code: "TG", name: "Togo", phoneFormat: "XX XX XX XX" },
  { code: "TO", name: "Tonga", phoneFormat: "XX XXXX" },
  { code: "TT", name: "Trinidad and Tobago", phoneFormat: "XXX XXXX" },
  { code: "TN", name: "Tunisia", phoneFormat: "XX XXX XXX" },
  { code: "TR", name: "Turkey", phoneFormat: "XXX XXX XXXX" },
  { code: "TM", name: "Turkmenistan", phoneFormat: "XX XXXXXX" },
  { code: "TV", name: "Tuvalu", phoneFormat: "XX XXXX" },
  { code: "UG", name: "Uganda", phoneFormat: "XXX XXX XXX" },
  { code: "UA", name: "Ukraine", phoneFormat: "XX XXX XX XX" },
  { code: "AE", name: "United Arab Emirates", phoneFormat: "XX XXX XXXX" },
  { code: "GB", name: "United Kingdom", phoneFormat: "XXXX XXX XXX" },
  { code: "US", name: "United States", phoneFormat: "XXX XXX XXXX" },
  { code: "UY", name: "Uruguay", phoneFormat: "X XXX XXXX" },
  { code: "UZ", name: "Uzbekistan", phoneFormat: "XX XXX XX XX" },
  { code: "VU", name: "Vanuatu", phoneFormat: "XXX XXXX" },
  { code: "VA", name: "Vatican City", phoneFormat: "XXXX XXXX" },
  { code: "VE", name: "Venezuela", phoneFormat: "XXX XXX XXXX" },
  { code: "VN", name: "Vietnam", phoneFormat: "XX XXX XXXX" },
  { code: "YE", name: "Yemen", phoneFormat: "XXX XXX XXX" },
  { code: "ZM", name: "Zambia", phoneFormat: "XX XXX XXXX" },
  { code: "ZW", name: "Zimbabwe", phoneFormat: "XX XXX XXXX" }
];

// Add flag image URL to each country
COUNTRIES.forEach((c) => {
  c.flagSrc = flagUrl(c.code);
  c.flag = c.code; // fallback text
});

const PHONE_PREFIXES = COUNTRIES.map((c) => ({
  flag: c.flag,
  code: c.code,
  name: c.name,
  phoneFormat: c.phoneFormat
}));

// Phone prefix to dial code mapping
const DIAL_CODES = {
  AF: "+93", AL: "+355", DZ: "+213", AD: "+376", AO: "+244", AG: "+1-268",
  AR: "+54", AM: "+374", AU: "+61", AT: "+43", AZ: "+994",
  BS: "+1-242", BH: "+973", BD: "+880", BB: "+1-246", BY: "+375", BE: "+32",
  BZ: "+501", BJ: "+229", BT: "+975", BO: "+591", BA: "+387", BW: "+267",
  BR: "+55", BN: "+673", BG: "+359", BF: "+226", BI: "+257",
  CV: "+238", KH: "+855", CM: "+237", CA: "+1", CF: "+236", TD: "+235",
  CL: "+56", CN: "+86", CO: "+57", KM: "+269", CG: "+242", CD: "+243",
  CR: "+506", CI: "+225", HR: "+385", CU: "+53", CY: "+357", CZ: "+420",
  DK: "+45", DJ: "+253", DM: "+1-767", DO: "+1-809", DO: "+1-829", DO: "+1-849",
  EC: "+593", EG: "+20", SV: "+503", GQ: "+240", ER: "+291", EE: "+372",
  SZ: "+268", ET: "+251",
  FJ: "+679", FI: "+358", FR: "+33",
  GA: "+241", GM: "+220", GE: "+995", DE: "+49", GH: "+233", GR: "+30",
  GD: "+1-473", GT: "+502", GN: "+224", GW: "+245", GY: "+592",
  HT: "+509", HN: "+504", HU: "+36",
  IS: "+354", IN: "+91", ID: "+62", IR: "+98", IQ: "+964", IE: "+353",
  IT: "+39",
  JM: "+1-876", JP: "+81", JO: "+962",
  KZ: "+7", KE: "+254", KI: "+686", XK: "+383", KW: "+965", KG: "+996",
  LA: "+856", LV: "+371", LB: "+961", LS: "+266", LR: "+231", LY: "+218",
  LI: "+423", LT: "+370", LU: "+352",
  MG: "+261", MW: "+265", MY: "+60", MV: "+960", ML: "+223", MT: "+356",
  MH: "+692", MR: "+222", MU: "+230", MX: "+52", FM: "+691", MD: "+373",
  MC: "+377", MN: "+976", ME: "+382", MA: "+212", MZ: "+258", MM: "+95",
  NA: "+264", NR: "+674", NP: "+977", NL: "+31", NZ: "+64", NI: "+505",
  NE: "+227", NG: "+234", KP: "+850", MK: "+389", NO: "+47",
  OM: "+968",
  PK: "+92", PW: "+680", PS: "+970", PA: "+507", PG: "+675", PY: "+595",
  PE: "+51", PH: "+63", PL: "+48", PT: "+351",
  QA: "+974",
  RO: "+40", RU: "+7", RW: "+250",
  KN: "+1-869", LC: "+1-758", VC: "+1-784", WS: "+685", SM: "+378",
  ST: "+239", SA: "+966", SN: "+221", RS: "+381", SC: "+248", SL: "+232",
  SG: "+65", SK: "+421", SI: "+386", SB: "+677", SO: "+252", ZA: "+27",
  KR: "+82", SS: "+211", ES: "+34", LK: "+94", SD: "+249", SR: "+597",
  SE: "+46", CH: "+41", SY: "+963",
  TW: "+886", TJ: "+992", TZ: "+255", TH: "+66", TL: "+670", TG: "+228",
  TO: "+676", TT: "+1-868", TN: "+216", TR: "+90", TM: "+993", TV: "+688",
  UG: "+256", UA: "+380", AE: "+971", GB: "+44", US: "+1", UY: "+598",
  UZ: "+998",
  VU: "+678", VA: "+379", VE: "+58", VN: "+84",
  YE: "+967",
  ZM: "+260", ZW: "+263"
};

// Build full PHONE_DATA with dial codes
const PHONE_DATA = COUNTRIES.map((c) => ({
  flagSrc: c.flagSrc,
  flag: c.flag,
  code: c.code,
  dial: DIAL_CODES[c.code] || "+" + c.code,
  name: c.name,
  phoneFormat: c.phoneFormat
}));

export function getCountryByCode(code) {
  return COUNTRIES.find((c) => c.code === code) || null;
}

export function getCountryByName(name) {
  return COUNTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase()) || null;
}

export function getPhoneDataByCode(code) {
  return PHONE_DATA.find((p) => p.code === code) || null;
}

export function getPhoneDataByDial(dial) {
  return PHONE_DATA.find((p) => p.dial === dial) || null;
}

export { PHONE_DATA, DIAL_CODES };
export default COUNTRIES;